### ISSUE TITLE
Retry failed on Riemann process restart

### ISSUE THREAD

**Issue by kevinverhoeven** [greglook/solanum#14]
Version 3.1.2

We recently restarted the Riemann process and all our Solanum hosts stopped sending metrics. Looking into the journal log, `sudo journalctl -u solanum`, I see the connection close, but no retry. Please configure the process to exit on connection close and systemd should restart the failed process if set to always retry.

**Comment by kevinverhoeven** [comment]
Stack trace:

`Apr 18 16:33:39 datanode-0 sh[10948]: 2019-04-18 16:33:39,191 [solanum-writer]     WARN  i.n.channel.AbstractChannel     Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x2921d472]
Apr 18 16:33:39 datanode-0 sh[10948]: java.util.concurrent.RejectedExecutionException: event executor terminated                                                                             
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Throwable.<init>(Throwable.java:265)                                                
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Exception.<init>(Exception.java:66)                                                                                                                              
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.RuntimeException.<init>(RuntimeException.java:62)                                     
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.util.concurrent.RejectedExecutionException.<init>(RejectedExecutionException.java:64)      
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)                                               
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)                                                                           
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)                                              
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:479)            
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)            
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)               
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)          
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)              
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)                               
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)                                      
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.TcpTransport.connect(TcpTransport.java:217)                         
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.TcpTransport.reconnect(TcpTransport.java:255)          
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.RiemannClient.reconnect(RiemannClient.java:194)        
Apr 18 16:33:39 datanode-0 sh[10948]:         at riemann.client$reconnect_BANG_.invokeStatic(client.clj:107)                      
Apr 18 16:33:39 datanode-0 sh[10948]:         at riemann.client$reconnect_BANG_.invoke(client.clj:104)                             
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.output.riemann.RiemannOutput.write_events(riemann.clj:48)                
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs$write__1938.invoke(writer.clj:18)                    
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_$fn__8431.invoke(core.clj:7635)                                 
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)                 
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$reduce.invokeStatic(core.clj:6747)                                       
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_.invokeStatic(core.clj:7630)                              
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_.invoke(core.clj:7630)                             
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs.invokeStatic(writer.clj:13)               
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs.invoke(writer.clj:9)                        
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$writer_loop$writer__1944.invoke(writer.clj:42)          
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.lang.AFn.run(AFn.java:22)                                        
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Thread.run(Thread.java:748)                            
Apr 18 16:33:39 datanode-0 sh[10948]:         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:476)
Apr 18 16:33:39 datanode-0 sh[10948]:         at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
Apr 18 16:33:39 datanode-0 sh[10948]: 2019-04-18 16:33:39,206 [solanum-writer]     ERROR i.n.u.c.D.rejectedExecution     Failed to submit a listener notification task. Event loop shut down?
Apr 18 16:33:39 datanode-0 sh[10948]: java.util.concurrent.RejectedExecutionException: event executor terminated
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Throwable.<init>(Throwable.java:265)                 
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Exception.<init>(Exception.java:66)    
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.RuntimeException.<init>(RuntimeException.java:62)                    
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.util.concurrent.RejectedExecutionException.<init>(RejectedExecutionException.java:64)      
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)                                               
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)                    
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)                                                            
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)                     
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)                                                            
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)             
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:490)            
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)                                                                                             
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)    
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)                                                                                           
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)                            
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)                                      
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.TcpTransport.connect(TcpTransport.java:217)                         
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.TcpTransport.reconnect(TcpTransport.java:255)                      
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.RiemannClient.reconnect(RiemannClient.java:194)                       
Apr 18 16:33:39 datanode-0 sh[10948]:         at riemann.client$reconnect_BANG_.invokeStatic(client.clj:107)                                   
Apr 18 16:33:39 datanode-0 sh[10948]:         at riemann.client$reconnect_BANG_.invoke(client.clj:104)                                           
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.output.riemann.RiemannOutput.write_events(riemann.clj:48)                             
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs$write__1938.invoke(writer.clj:18)                                
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_$fn__8431.invoke(core.clj:7635)                                           
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)                       
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$reduce.invokeStatic(core.clj:6747)                                 
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_.invokeStatic(core.clj:7630)                                    
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_.invoke(core.clj:7630)                                    
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs.invokeStatic(writer.clj:13)                                  
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs.invoke(writer.clj:9)                                            
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$writer_loop$writer__1944.invoke(writer.clj:42) 
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.lang.AFn.run(AFn.java:22)
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Thread.run(Thread.java:748)
Apr 18 16:33:39 datanode-0 sh[10948]:         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:476)
Apr 18 16:33:39 datanode-0 sh[10948]:         at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
Apr 18 16:33:39 datanode-0 sh[10948]: 2019-04-18 16:33:39,206 [solanum-writer]     ERROR i.n.u.c.D.rejectedExecution     Failed to submit a listener notification task. Event loop shut down?
Apr 18 16:33:39 datanode-0 sh[10948]: java.util.concurrent.RejectedExecutionException: event executor terminated
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Throwable.<init>(Throwable.java:265)
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Exception.<init>(Exception.java:66)
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.RuntimeException.<init>(RuntimeException.java:62)
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.util.concurrent.RejectedExecutionException.<init>(RejectedExecutionException.java:64)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:491)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.TcpTransport.connect(TcpTransport.java:217)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.TcpTransport.reconnect(TcpTransport.java:255)
Apr 18 16:33:39 datanode-0 sh[10948]:         at io.riemann.riemann.client.RiemannClient.reconnect(RiemannClient.java:194)
Apr 18 16:33:39 datanode-0 sh[10948]:         at riemann.client$reconnect_BANG_.invokeStatic(client.clj:107)
Apr 18 16:33:39 datanode-0 sh[10948]:         at riemann.client$reconnect_BANG_.invoke(client.clj:104)
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.output.riemann.RiemannOutput.write_events(riemann.clj:48)
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs$write__1938.invoke(writer.clj:18)
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_$fn__8431.invoke(core.clj:7635)
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$reduce.invokeStatic(core.clj:6747)
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_.invokeStatic(core.clj:7630)
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.core$run_BANG_.invoke(core.clj:7630)
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs.invokeStatic(writer.clj:13)
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$write_outputs.invoke(writer.clj:9)
Apr 18 16:33:39 datanode-0 sh[10948]:         at solanum.writer$writer_loop$writer__1944.invoke(writer.clj:42)
Apr 18 16:33:39 datanode-0 sh[10948]:         at clojure.lang.AFn.run(AFn.java:22)
Apr 18 16:33:39 datanode-0 sh[10948]:         at java.lang.Thread.run(Thread.java:748)
Apr 18 16:33:39 datanode-0 sh[10948]:         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:476)
Apr 18 16:33:39 datanode-0 sh[10948]:         at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)`

**Comment by greglook** [comment]
Fixed in [3.2.1](https://github.com/greglook/solanum/releases/tag/3.2.1).
